# Generated by Django 3.2 on 2023-05-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=10, verbose_name='Время в минутах'),
            preserve_default=False,
        ),
    ]
