# Generated by Django 3.2 on 2023-05-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_foodgramuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgramuser',
            name='is_subscribed',
        ),
    ]
